[extend]
# Use the default gitleaks config as a base
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[allowlist]
description = "Global allowlist"

paths = [
    '''go\.sum''',
]

commits = [
    # Initial commit containing example curl with placeholder credentials in api-research.md
    "05e97349065ee0ec6a5302e30a2d23fb565f84bd",
]
